## DataFrame
Usually we work with two-dimensional arrays. We store them using **DataFrame** in pandas. 

### Activity
Let's use a DataFrame to store more meaningful values than our countries series. Let's store the following values in a Data Frame called 'big_mac':

**Headings:** Country, Local Price, AUD Price
- `'Australia', 7.45, 7.45`
- `'Britain', 4.19, 0.0`
- `'Japan', 450, 0.0`
- `'New Zealand', 7.1, 0.0`
- `'United States', 5.58, 0.0`

**NOTE:** You'll need to look online at current rates to convert Britain, New Zealand, Japan and United States' local prices to AUD.

In [4]:
import pandas as pd
#Add a pandas DataFrame called 'big_mac' with the above values
Aud_price_convert = pd.DataFrame([
                                ['Australia', 7.45,7.45],
                                ['Britain',4.19,8.06],
                                ['Japan', 450,4.06],
                                ['New Zealand', 5.58, 4.66],
                                ['United States',5.58,8.03],
                                ],
                                columns= ['Country','Local Price','AUD Price']
                                )
#Print the DataFrame
Aud_price_convert

         Country  Local Price  AUD Price
0      Australia         7.45       7.45
1        Britain         4.19       8.06
2          Japan       450.00       4.06
3    New Zealand         5.58       4.66
4  United States         5.58       8.03

## Examining pandas DataFrames

In [5]:
#Print only the first two rows of the big_mac dataframe

Aud_price_convert.head(2)

     Country  Local Price  AUD Price
0  Australia         7.45       7.45
1    Britain         4.19       8.06

In [6]:
#Print only the last four rows of the big_mac dataframe
Aud_price_convert.tail(4)

         Country  Local Price  AUD Price
1        Britain         4.19       8.06
2          Japan       450.00       4.06
3    New Zealand         5.58       4.66
4  United States         5.58       8.03

In [7]:
#Print the number of rows and columns in the big_mac dataframe
Aud_price_convert.shape

(5, 3)

In [13]:
#Print some detailed information about the big_mac dataframe
Aud_price_convert.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Country      5 non-null      str
 1   Local Price  5 non-null      float64
 2   AUD Price    5 non-null      float64
dtypes: float64(2), str(1)
memory usage: 252.0 bytes

## Querying DataFrames
Let's explore how we request data from a pandas DataFrame.

In [14]:
#Request and output the 'Country' and 'AUD Price' columns from the big_mac DataFrame.
Aud_price_convert[['Country','AUD Price']]

         Country  AUD Price
0      Australia       7.45
1        Britain       8.06
2          Japan       4.06
3    New Zealand       4.66
4  United States       8.03

In [15]:
#Use iloc to request the third row, all columns
Aud_price_convert.iloc[2,:]

Country        Japan
Local Price    450.0
AUD Price       4.06
Name: 2, dtype: object

In [18]:
#Use iloc to request all rows, but just the 'Country' and 'AUD Price' columns

Aud_price_convert.iloc[:,::2]

         Country  AUD Price
0      Australia       7.45
1        Britain       8.06
2          Japan       4.06
3    New Zealand       4.66
4  United States       8.03

In [21]:
#Use loc to do the same thing as the previous (Country and AUD Price all rows)
Aud_price_convert.loc[:,['Country','AUD Price']]

         Country  AUD Price
0      Australia       7.45
1        Britain       8.06
2          Japan       4.06
3    New Zealand       4.66
4  United States       8.03